### ISSUE TITLE
Main feature of the app

### ISSUE THREAD

**Issue by fedebyes** [Starnino/Doctor-Finder#6]
What's the main feature of the app?

**Comment by GiovanniGiampaolo** [comment]
research of the doctor quickly and concrete

**Comment by fedebyes** [comment]
Find the best healt specialist for your needs
Search doctor’s information like
Name
Surname
Photo
Specialization
Availability
Feedback

See a map of the doctors around you
Contact directly the doctor (Videocall)
User involvement
Social integration
